AWSTemplateFormatVersion: "2010-09-09"
Description: "necro assume role"

Parameters:
  RoleName:
    Type: String
    Description: "IAM role name (e.g. role-com-prd-necro)"
  BucketName:
    Type: String
    Description: "Artifact bucket name (e.g. s3-com-prd-necro-artifact)"
  TrustedAccountId:
    Type: String
    AllowedPattern: "^[0-9]{12}$"
    Description: "Trusted AWS Account ID (root principal) that can assume this role"

Resources:
  NecroAssumeRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Ref RoleName
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: AllowAssumeFromTrustedRoot
            Effect: Allow
            Principal:
              AWS: !Sub "arn:aws:iam::${TrustedAccountId}:root"
            Action: "sts:AssumeRole"

      # AWS managed policies (ReadOnly)
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/ReadOnlyAccess"

      # Inline policy (Full access to the specific bucket)
      Policies:
        - PolicyName: NecroBucketFullAccess
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Sid: BucketAndObjectsFullAccess
                Effect: Allow
                Action:
                  - "s3:*"
                Resource:
                  - !Sub "arn:aws:s3:::${BucketName}"
                  - !Sub "arn:aws:s3:::${BucketName}/*"

Outputs:
  RoleArn:
    Value: !GetAtt NecroAssumeRole.Arn
  RoleName:
    Value: !Ref RoleName
  BucketName:
    Value: !Ref BucketName
  TrustedPrincipal:
    Value: !Sub "arn:aws:iam::${TrustedAccountId}:root"