version: 1

defaults:
  region: ap-northeast-1

targets:
  profiles: [
    "COM_PRD"
  ] # 空なら ~/.aws/config から自動取得
  exclude:
    - SAMPLE_PROFILE

vars: # build-in var: PROFILE, REGION, ACCOUNT_ID, RUN_ID
  template-resolve-limit: 10

  defaults:
    SYSTEM: '{{ (splitList "_" .PROFILE | first | lower) }}'
    ENV: '{{ (splitList "_" .PROFILE | last | lower) }}'
    AWS_CONFIG_TEMPLATE: "conf/sample/operation/generate_aws_config/aws_config_template.txt"
    JQ_SSO_ROLE_NAME: 'ps-org-admin-for-\(.System)-\(.Env)'

  # profiles:
  #   COM_PRD:
  #     SYSTEM: com
  #     ENV: prd

cmd:
  ## Organizationsアカウント(一覧)
  - name: organizations_list-accounts
    aws: ["organizations", "list-accounts"]
    out: "./out/{{ .PROFILE }}/org-accounts.json"
  ## Organizationsアカウント一覧 -> NDJSON（1アカウント1行）に整形
  - name: org-account-list-slim
    sh: >
      jq -c '
        .Accounts[]
        | .Name as $name
        | ($name | split("_")) as $p
        | {
            profile: $name,
            account_id: .Id,
            system: ($p[0] | ascii_downcase),
            env: ($p[1] | ascii_downcase)
          }
      '
    in: "./out/{{ .PROFILE }}/org-accounts.json"
    out: "./out/{{ .PROFILE }}/org-account-list.jsonl"
  ## Organizationsアカウント一覧(JSON) -> aws_config_template.txt と結合して aws_config.txt生成
  - name: org-account-list-to-aws-config
    sh: >
      cat {{ .AWS_CONFIG_TEMPLATE }};
      echo "";
      echo ";; GENERATED CODE DO NOT DELETE";
      echo "";
      jq -r '
        .Accounts
        | map(
            .Name as $name
            | ($name | split("_")) as $parts
            | {
                Id: .Id,
                Name: $name,
                System: ($parts[0] | ascii_downcase),
                Env: ($parts[1] | ascii_downcase)
              }
          )
        | .[]
        | "[profile \(.Name)]",
          "region = ap-northeast-1",
          "sso_account_id = \(.Id)",
          "sso_session = AWS_SESSION",
          "sso_role_name = {{ .JQ_SSO_ROLE_NAME }}",
          ""
      '
    in: "./out/{{ .PROFILE }}/org-accounts.json"
    out: "./out/aws_config.txt"
  